sbatch slurm/at-rtx.sbatch uv run state tx train \
  data.kwargs.toml_config_path="examples/hvg_2000.toml" \
  data.kwargs.embed_key="X_hvg" \
  data.kwargs.output_space="all" \
  data.kwargs.basal_rep="sample" \
  data.kwargs.num_workers=8 \
  data.kwargs.pin_memory=true \
  data.kwargs.n_basal_samples=1 \
  data.kwargs.basal_mapping_strategy="random" \
  data.kwargs.should_yield_control_cells=true \
  data.kwargs.batch_col="batch_var" \
  data.kwargs.pert_col="target_gene" \
  data.kwargs.cell_type_key="cell_type" \
  data.kwargs.control_pert="non-targeting" \
  data.kwargs.map_controls=true \
  data.kwargs.perturbation_features_file="assets/ST-Tahoe/pert_onehot_map.pt" \
  data.kwargs.store_raw_basal=false \
  data.kwargs.int_counts=false \
  data.kwargs.barcode=true \
  training.weight_decay=0.00005 \
  training.batch_size=32 \
  training.lr=0.0001 \
  training.max_steps=40000 \
  training.train_seed=42 \
  training.ckpt_every_n_steps=500 \
  training.gradient_clip_val=5 \
  training.loss_fn=mse \
  model=st-tahoe-lb-metric \
  use_wandb=true \
  wandb.tags="[stt-dec-mod]" \
  wandb.project=state-arc \
  wandb.entity=a-mete-2416 \
  output_dir="experiments/" \
  name="stt-dec-mod"


sbatch slurm/at-rtx.sbatch uv run state tx train \
  data.kwargs.toml_config_path="examples/hvg_2000.toml" \
  data.kwargs.embed_key="X_hvg" \
  data.kwargs.output_space="all" \
  data.kwargs.basal_rep="sample" \
  data.kwargs.num_workers=8 \
  data.kwargs.pin_memory=true \
  data.kwargs.n_basal_samples=1 \
  data.kwargs.basal_mapping_strategy="random" \
  data.kwargs.should_yield_control_cells=true \
  data.kwargs.batch_col="batch_var" \
  data.kwargs.pert_col="target_gene" \
  data.kwargs.cell_type_key="cell_type" \
  data.kwargs.control_pert="non-targeting" \
  data.kwargs.map_controls=true \
  data.kwargs.perturbation_features_file="assets/ST-Tahoe/pert_onehot_map.pt" \
  data.kwargs.store_raw_basal=false \
  data.kwargs.int_counts=false \
  data.kwargs.barcode=true \
  training.weight_decay=0.00005 \
  training.batch_size=32 \
  training.lr=0.0001 \
  training.max_steps=40000 \
  training.train_seed=42 \
  training.ckpt_every_n_steps=500 \
  training.gradient_clip_val=5 \
  training.loss_fn=mse \
  model=st-tahoe-lb-metric \
  model.kwargs.sinkhorn_weight=0.05 \
  use_wandb=true \
  wandb.tags="[stt-dec-agg]" \
  wandb.project=state-arc \
  wandb.entity=a-mete-2416 \
  output_dir="experiments/" \
  name="stt-dec-agg"


sbatch slurm/at-rtx.sbatch uv run state tx train \
  data.kwargs.toml_config_path="examples/hvg_2000.toml" \
  data.kwargs.embed_key="X_hvg" \
  data.kwargs.output_space="all" \
  data.kwargs.basal_rep="sample" \
  data.kwargs.num_workers=8 \
  data.kwargs.pin_memory=true \
  data.kwargs.n_basal_samples=1 \
  data.kwargs.basal_mapping_strategy="random" \
  data.kwargs.should_yield_control_cells=true \
  data.kwargs.batch_col="batch_var" \
  data.kwargs.pert_col="target_gene" \
  data.kwargs.cell_type_key="cell_type" \
  data.kwargs.control_pert="non-targeting" \
  data.kwargs.map_controls=true \
  data.kwargs.perturbation_features_file="assets/ST-Tahoe/pert_onehot_map.pt" \
  data.kwargs.store_raw_basal=false \
  data.kwargs.int_counts=false \
  data.kwargs.barcode=true \
  training.weight_decay=0.00005 \
  training.batch_size=32 \
  training.lr=0.0001 \
  training.max_steps=40000 \
  training.train_seed=42 \
  training.ckpt_every_n_steps=500 \
  training.gradient_clip_val=5 \
  training.loss_fn=mse \
  model=st-tahoe-lb-metric \
  model.kwargs.loss="sinkhorn" \
  use_wandb=true \
  wandb.tags="[stt-dec-sink]" \
  wandb.project=state-arc \
  wandb.entity=a-mete-2416 \
  output_dir="experiments/" \
  name="stt-dec-sink"


sbatch slurm/at-rtx.sbatch uv run state tx train \
  data.kwargs.toml_config_path="examples/hvg_2000.toml" \
  data.kwargs.embed_key="X_hvg" \
  data.kwargs.output_space="all" \
  data.kwargs.basal_rep="sample" \
  data.kwargs.num_workers=8 \
  data.kwargs.pin_memory=true \
  data.kwargs.n_basal_samples=1 \
  data.kwargs.basal_mapping_strategy="random" \
  data.kwargs.should_yield_control_cells=true \
  data.kwargs.batch_col="batch_var" \
  data.kwargs.pert_col="target_gene" \
  data.kwargs.cell_type_key="cell_type" \
  data.kwargs.control_pert="non-targeting" \
  data.kwargs.map_controls=true \
  data.kwargs.perturbation_features_file="assets/ST-Tahoe/pert_onehot_map.pt" \
  data.kwargs.store_raw_basal=false \
  data.kwargs.int_counts=false \
  data.kwargs.barcode=true \
  training.weight_decay=0.00005 \
  training.batch_size=32 \
  training.lr=0.0001 \
  training.max_steps=40000 \
  training.train_seed=42 \
  training.ckpt_every_n_steps=500 \
  training.gradient_clip_val=5 \
  training.loss_fn=mse \
  model=st-tahoe-lb-metric \
  model.kwargs.confidence_token=true \
  use_wandb=true \
  wandb.tags="[stt-dec-mod-conf]" \
  wandb.project=state-arc \
  wandb.entity=a-mete-2416 \
  output_dir="experiments/" \
  name="stt-dec-mod-conf"


sbatch slurm/at-rtx.sbatch uv run state tx train \
  data.kwargs.toml_config_path="examples/hvg_2000.toml" \
  data.kwargs.embed_key="X_hvg" \
  data.kwargs.output_space="all" \
  data.kwargs.basal_rep="sample" \
  data.kwargs.num_workers=8 \
  data.kwargs.pin_memory=true \
  data.kwargs.n_basal_samples=1 \
  data.kwargs.basal_mapping_strategy="random" \
  data.kwargs.should_yield_control_cells=true \
  data.kwargs.batch_col="batch_var" \
  data.kwargs.pert_col="target_gene" \
  data.kwargs.cell_type_key="cell_type" \
  data.kwargs.control_pert="non-targeting" \
  data.kwargs.map_controls=true \
  data.kwargs.perturbation_features_file="assets/ST-Tahoe/pert_onehot_map.pt" \
  data.kwargs.store_raw_basal=false \
  data.kwargs.int_counts=false \
  data.kwargs.barcode=true \
  training.weight_decay=0.00005 \
  training.batch_size=32 \
  training.lr=0.0001 \
  training.max_steps=40000 \
  training.train_seed=42 \
  training.ckpt_every_n_steps=500 \
  training.gradient_clip_val=5 \
  training.loss_fn=mse \
  model=st-tahoe-lb-metric \
  model.kwargs.nb_decoder=true \
  use_wandb=true \
  wandb.tags="[stt-dec-nb-mod]" \
  wandb.project=state-arc \
  wandb.entity=a-mete-2416 \
  output_dir="experiments/" \
  name="stt-dec-nb-mod"


sbatch slurm/at-rtx.sbatch uv run state tx train \
  data.kwargs.toml_config_path="examples/hvg_2000.toml" \
  data.kwargs.embed_key="X_hvg" \
  data.kwargs.output_space="all" \
  data.kwargs.basal_rep="sample" \
  data.kwargs.num_workers=8 \
  data.kwargs.pin_memory=true \
  data.kwargs.n_basal_samples=1 \
  data.kwargs.basal_mapping_strategy="random" \
  data.kwargs.should_yield_control_cells=true \
  data.kwargs.batch_col="batch_var" \
  data.kwargs.pert_col="target_gene" \
  data.kwargs.cell_type_key="cell_type" \
  data.kwargs.control_pert="non-targeting" \
  data.kwargs.map_controls=true \
  data.kwargs.perturbation_features_file="assets/ST-Tahoe/pert_onehot_map.pt" \
  data.kwargs.store_raw_basal=false \
  data.kwargs.int_counts=false \
  data.kwargs.barcode=true \
  training.weight_decay=0.00005 \
  training.batch_size=32 \
  training.lr=0.0001 \
  training.max_steps=40000 \
  training.train_seed=42 \
  training.ckpt_every_n_steps=500 \
  training.gradient_clip_val=5 \
  training.loss_fn=mse \
  model=st-tahoe-lb-metric \
  model.kwargs.nb_decoder=true \
  model.kwargs.sinkhorn_weight=1.0 \
  use_wandb=true \
  wandb.tags="[stt-dec-nb-veryagg]" \
  wandb.project=state-arc \
  wandb.entity=a-mete-2416 \
  output_dir="experiments/" \
  name="stt-dec-nb-veryagg"